Enable robot_manager.py to communicate with go1 controller to synchronize task reset
Arena-Rosnav/arena-rosnav pull request #113
Opened 2024-01-08 19:24 UTC by aqubits

2024-01-09 14:54 UTC, linhdoan8 commented
@voshch pls test and merge

2024-01-09 15:04 UTC, voshch commented
resolve conflicts first

2024-01-10 14:12 UTC, voshch requested changes

2024-01-10 14:12 UTC, voshch commented on task_generator/task_generator/tasks/base_task.py
> +import os
undo

2024-01-10 14:13 UTC, voshch commented
This adds hard-coded logic in the task manager; push this to a separate branch (e.g. arena-rosnav:go1) and keep that branch synchronized with master.

2024-01-10 14:13 UTC, closed without merging